// easy-ring-demo/src/views/CommonDemo.vue
<template>
  <div class="home">
    <button @click="openRing">打开铃声</button>
    <div v-for="(msg, index) in msgs" :key="index" @click="read">
      {{msg}}
    </div>
  </div>
</template>

<script>
// @ is an alias to /src
import { CommonEasyRing } from 'easy-ring'

export default {
  data: () => ({
    msgs: [],
    frequency: 0.1,
    myCommonEasyRing: null
  }),
  methods: {
    polling() {
      setInterval(() => {
        console.log('请求中...')
        if (Math.random() > (1 - this.frequency)) {
          this.msgs.push('收到一条信息（请点击我来关铃）')
          this.myCommonEasyRing.ring()
        }
      }, 1000)
    },
    read() {
      this.myCommonEasyRing.stop()
    },
    openRing() {
      this.myCommonEasyRing.open()
    }
  },
  mounted() {
    this.polling()
    this.myCommonEasyRing = new CommonEasyRing({
      loop: false,
      log: true
    })
  }
}
</script>

// easy-ring-demo-react/src/components/CommonDemo.jsx
import React from "react"
import { CommonEasyRing } from 'easy-ring'
// const { CommonEasyRing } = require('easy-ring')

export default class Demo extends React.Component{
    constructor(props) {
        super(props)
        this.state = {
            msgs: [],
            frequency: 0.1,
            myCommonEasyRing: null
        }
        // 为了在回调中使用 `this`，这个绑定是必不可少的 。。。。
        this.openRing = this.openRing.bind(this)
        this.read = this.read.bind(this)
    }
    polling() {
      setInterval(() => {
        console.log('请求中...')
        if (Math.random() > (1 - this.state.frequency)) {
          this.setState({
            msgs: [...this.state.msgs, '收到一条信息（请点击我来关铃）'],
            ring: true
          })
          this.myCommonEasyRing.ring()
        }
      }, 1000)
    }
    read() {
      this.myCommonEasyRing.stop()
    }
    openRing() {
      this.myCommonEasyRing.open()
    }
    componentDidMount() {
        // 会调两次。解决：删掉/index.js的<StrictMode>(原因不明)
        this.polling()
        this.myCommonEasyRing = new CommonEasyRing({
            loop: true,
            log: false
        })
    }
    render() {
        return (<div className="home">
                    <button onClick={this.openRing}>打开铃声</button>
                    {
                        this.state.msgs.map((item, index) => (
                            <div onClick={this.read} key={index}>
                                {item}
                            </div>))
                    }
                </div>)
    }
}
