// easy-ring-demo-react/src/components/FunctionDemo.jsx
import { useState, useEffect } from 'react'
import { CommonEasyRing } from 'easy-ring'
import { Modal } from 'antd'
import Msg from '../utils/msg'
import {
    MessageOutlined
  } from '@ant-design/icons'
import { Badge, Dropdown, Menu } from 'antd';

const myEasyRing = new CommonEasyRing()
const msg = new Msg({
    frequency: 0.1
})


const FunctionDemo = () => {
    // const [myEasyRing, setMyEasyRing] = useState(null)
    const [isModalOpen, setIsModalOpen] = useState(true)
    const [intervalCount, setIntervalCount] = useState(0)
    const [newMsgCount, setNewMsgCount] = useState(0)
    const [msgList, setMsgList] = useState([])
    // const [msg, setMsg] = useState(null)

    const handleOk= () => {
        setIsModalOpen(false)
        myEasyRing.open()
    }
    const handleCancel= () => {
        setIsModalOpen(false)
    }

    const dropdownChange = (val) => {
        if (!val) {
            setNewMsgCount(0)
            setMsgList([])
        }
        myEasyRing.stop()
      }

    useEffect(() => {
        msg.listening()
        msg.onReceived((newMsg) => {
            myEasyRing.ring()
            setMsgList(list => [...list, newMsg])
            setNewMsgCount(count => count + 1)
        })
        setInterval(() => {
            setIntervalCount(count => count + 1)
        }, 1000)
        return () => {
            myEasyRing.stop() // TODO: 没法正确关闭的这个错误，还会影响easy-ring组件的loop？是因为音频元素没获取到（不是没生成）【感觉这块得弄成异步x】
            myEasyRing.close() // TODO: 关闭还会响
            msg.stopListening()
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])


    return (
        <div>
            <div style={{display: 'flex', justifyContent: 'center',alignItems: 'center', flexWrap: 'wrap', height: '200px'}}>
                <div style={{ flexBasis: '100%', display: 'flex', justifyContent: 'center'}}>
                    <Dropdown overlay={
                        <Menu
                            items={
                            msgList.map((m, i) => ({
                                label: `收到一条新信息！| Receive a new message!（ id = ${m.id}）`,
                                key: i
                            }))
                            }
                        />
                    } trigger={['click']} onOpenChange={dropdownChange}>
                        <Badge count={newMsgCount}>
                            <MessageOutlined style={{fontSize: '36px', cursor: 'pointer'}}/>
                        </Badge>
                    </Dropdown>
                </div>
                <div style={{display: 'flex', justifyContent: 'center', color: 'black'}}>
                    { newMsgCount === 0 ? (
                        <span>
                            正在接收消息... | Waiting message...{intervalCount}s
                        </span>
                    ) : (
                        <div style={{display: 'flex',justifyContent:'center',flexWrap: 'wrap'}}>
                            <div style={{flexBasis: '100%', textAlign: 'center'}}>你收到了新消息！ | You receive new messages!</div>
                            <div style={{marginTop: 30}}>(点击图标查看消息、并停止声音 | Click the icon to view the message and stop the sound.)</div>
                        </div>
                    ) }
                </div>
            </div>
            <Modal title="" open={isModalOpen} onOk={handleOk} onCancel={handleCancel}>
                <p>我们需要您同意开启声音 ｜ We need your consent to turn on sound.</p>
            </Modal>
        </div>
    )
}

export default FunctionDemo

// easy-ring-demo-vue2/src/components/FunctionDemo.vue
<template>
  <div class="msg">
    <el-dropdown trigger="click" @visible-change="dropdownChange">
      <div>
        <el-badge :value="newMsgCount" class="item" v-if="newMsgCount">
          <i style="font-size: 30px;" class="el-icon-message"></i>
        </el-badge>
        <i style="font-size: 30px;" class="el-icon-message" v-else></i>
      </div>
      <el-dropdown-menu slot="dropdown">
        <el-dropdown-item v-for="(m, i) in msgList" :key="i">
            收到一条新信息！| Receive a new message!（ id = {{m.id}}）
        </el-dropdown-item>
      </el-dropdown-menu>
    </el-dropdown>
    <div>
      <template v-if="newMsgCount === 0">
        正在接收消息... | Waiting message...({{intervalCount}}s)
      </template>
      <template v-else>
        <div style="display: flex;justify-content:center;flex-wrap: wrap;">
          <div style="flex-basis: 100%;">你收到了新消息！ | You receive new messages!</div>
          <div style="margin-top: 30px;">(点击图标查看消息、并停止声音 | Click the icon to view the message and stop the sound.)</div>
        </div>
      </template>
    </div>
  </div>
</template>

<script>
import Msg from '../utils/msg'
import { CommonEasyRing } from 'easy-ring'

const msg = new Msg({
  frequency: 0.1
})

export default {
  data() {
    return {
      currentMsgIndex: 0,
      newMsgCount: 0,
      msgList: [],
      myEasyRing: null,
      intervalCount: 0
    }
  },
  methods:{
    dropdownChange(val) {
      if (!val) {
        this.newMsgCount = 0
        this.msgList = []
      }
      this.myEasyRing.stop()
    }
  },
  mounted() {
    this.myEasyRing = new CommonEasyRing()

    this.$confirm('我们需要您同意开启声音 ｜ We need your consent to turn on sound.', '', {
      confirmButtonText: 'OK',
    }).then(() => {
      this.myEasyRing.open()
      // TODO: 需要强制切换一下？
    }).catch(() => {})
    msg.listening()
    msg.onReceived((newMsg) => {
      this.myEasyRing.ring()
      this.msgList.push(newMsg)
      this.newMsgCount = this.newMsgCount + 1
    }) 

    setInterval(() => {
      this.intervalCount += 1
    }, 1000)
  },
  beforeDestroy(){
    this.myEasyRing.stop() // TODO: 如果没打开，关闭会有问题
    this.myEasyRing.close() // TODO: 关闭还会响
    msg.stopListening()
  }
}
</script>

<style>
.msg {
  cursor: pointer;
}
.el-dropdown-menu__item {
  padding-right: 130px!important;
}
</style>
